// Shannon-Prime VHT2 - Hexagon DSP backend (host-side stub).
// Copyright (C) 2026 Ray Daniels. All Rights Reserved. AGPLv3 / commercial.
//
// THIS IS A SCAFFOLDING STUB. None of the Hexagon-side kernels exist yet;
// the functions in this file are placeholders that return -1 / NULL with
// a one-shot diagnostic message so the bridge can detect that the
// Hexagon path is unbuilt and fall back to Adreno/CPU.
//
// Implementation roadmap lives in lib/shannon-prime/docs/BACKEND-HEXAGON.md.
// Milestones M0..M3 there describe what each pass of work looks like, in
// what order, and what hardware/SDK is required.
//
// To build the real backend, this file gets paired with:
//   - dsp/shannon_prime_dsp.c    Hexagon-side HVX kernels (toolv87)
//   - shannon_prime_hexagon.idl  FastRPC interface definition
//   - sp_hexagon_skel.c           generated by qaic from the IDL
//   - sp_hexagon_stub.c           generated by qaic from the IDL
// None of these files exist yet - this stub keeps the SP build green
// while the real implementation lands incrementally.

#include "shannon_prime_hexagon.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ============================================================================
// Capability detection
// ============================================================================

int sp_hexagon_caps_probe(sp_hexagon_caps_t *caps) {
    if (!caps) return -1;
    memset(caps, 0, sizeof(*caps));
    // Real probe requires opening a FastRPC session and querying the
    // DSP firmware version. For now we just report 'unavailable' so
    // bridges fall back cleanly.
    return -1;
}

void sp_hexagon_caps_print(const sp_hexagon_caps_t *caps) {
    if (!caps) return;
    fprintf(stderr, "Hexagon DSP Capabilities:\n");
    fprintf(stderr, "  DSP accessible: %s\n", caps->has_dsp ? "yes" : "no");
    if (caps->has_dsp) {
        fprintf(stderr, "  DSP version:    V%d\n", caps->dsp_version);
        fprintf(stderr, "  HVX:            %s (%d-bit)\n",
                caps->has_hvx ? "yes" : "no", caps->hvx_width_bits);
        fprintf(stderr, "  HMX:            %s\n", caps->has_hmx ? "yes" : "no");
        fprintf(stderr, "  Threads:        %d\n", caps->max_threads);
        fprintf(stderr, "  Shared memory:  %lld bytes\n",
                (long long)caps->shared_mem_bytes);
    } else {
        fprintf(stderr, "  (DSP unavailable - SDK not built or device not "
                        "Snapdragon)\n");
    }
}

// ============================================================================
// Lifecycle stubs
// ============================================================================

sp_hexagon_ctx_t *sp_hexagon_init(const sp_config_t *cfg) {
    (void)cfg;
    static int warned = 0;
    if (!warned) {
        fprintf(stderr,
            "[Shannon-Prime] Hexagon backend is not yet built. The header "
            "shannon_prime_hexagon.h declares the API, but the FastRPC IDL + "
            "DSP-side HVX kernels haven't been written. See "
            "lib/shannon-prime/docs/BACKEND-HEXAGON.md for the implementation "
            "roadmap. Falling back to Adreno or CPU backend.\n");
        warned = 1;
    }
    return NULL;
}

void sp_hexagon_free(sp_hexagon_ctx_t *ctx) {
    (void)ctx;
}

// ============================================================================
// Memory + round-trip stubs
// ============================================================================

void *sp_hexagon_alloc(sp_hexagon_ctx_t *ctx, size_t n_bytes) {
    (void)ctx; (void)n_bytes;
    return NULL;
}

void sp_hexagon_free_shared(sp_hexagon_ctx_t *ctx, void *ptr) {
    (void)ctx; (void)ptr;
}

int sp_hexagon_round_trip_k(sp_hexagon_ctx_t *ctx,
                             const uint16_t *in_fp16, uint16_t *out_fp16) {
    (void)ctx; (void)in_fp16; (void)out_fp16;
    return -1;
}

int sp_hexagon_round_trip_v(sp_hexagon_ctx_t *ctx,
                             const uint16_t *in_fp16, uint16_t *out_fp16) {
    (void)ctx; (void)in_fp16; (void)out_fp16;
    return -1;
}

int sp_hexagon_round_trip_k_batch(sp_hexagon_ctx_t *ctx,
                                   const uint16_t *in_fp16, uint16_t *out_fp16,
                                   int n_vectors) {
    (void)ctx; (void)in_fp16; (void)out_fp16; (void)n_vectors;
    return -1;
}

int sp_hexagon_band_dequantize_partial(sp_hexagon_ctx_t *ctx,
                                        const uint8_t *in_packed,
                                        uint16_t *out_fp16,
                                        int max_bands) {
    (void)ctx; (void)in_packed; (void)out_fp16; (void)max_bands;
    return -1;
}

// ============================================================================
// Diagnostics stubs
// ============================================================================

size_t sp_hexagon_memory_in_use(const sp_hexagon_ctx_t *ctx) {
    (void)ctx;
    return 0;
}

long long sp_hexagon_last_call_cycles(const sp_hexagon_ctx_t *ctx) {
    (void)ctx;
    return 0;
}
