/* sp_hex_mobius_tables.c — auto-generated by
 * scripts/gen_mobius_tables.py.  Compile-time byte-offset tables
 * for HVX vscatter-based Möbius reorder, one per supported
 * head_dim.  See the script docstring for the math derivation.
 *
 * DO NOT EDIT BY HAND — regenerate via:
 *   python scripts/gen_mobius_tables.py
 */

#include "sp_hex_mobius_tables.h"

/* head_dim=64, n_squarefree=39, element_size=4.  Byte offsets for vscatter into a 256-byte VTCM region. */
static const uint32_t sp_hex_mobius_offsets_hd64_f32[64] __attribute__((aligned(128))) = {
      156u,     0u,     4u,     8u,   160u,    12u,    16u,    20u,
      164u,   168u,    24u,    28u,   172u,    32u,    36u,    40u,
      176u,    44u,   180u,    48u,   184u,    52u,    56u,    60u,
      188u,   192u,    64u,   196u,   200u,    68u,    72u,    76u,
      204u,    80u,    84u,    88u,   208u,    92u,    96u,   100u,
      212u,   104u,   108u,   112u,   216u,   220u,   116u,   120u,
      224u,   228u,   232u,   124u,   236u,   128u,   240u,   132u,
      244u,   136u,   140u,   144u,   248u,   148u,   152u,   252u,
};

/* head_dim=128, n_squarefree=78, element_size=4.  Byte offsets for vscatter into a 512-byte VTCM region. */
static const uint32_t sp_hex_mobius_offsets_hd128_f32[128] __attribute__((aligned(128))) = {
      312u,     0u,     4u,     8u,   316u,    12u,    16u,    20u,
      320u,   324u,    24u,    28u,   328u,    32u,    36u,    40u,
      332u,    44u,   336u,    48u,   340u,    52u,    56u,    60u,
      344u,   348u,    64u,   352u,   356u,    68u,    72u,    76u,
      360u,    80u,    84u,    88u,   364u,    92u,    96u,   100u,
      368u,   104u,   108u,   112u,   372u,   376u,   116u,   120u,
      380u,   384u,   388u,   124u,   392u,   128u,   396u,   132u,
      400u,   136u,   140u,   144u,   404u,   148u,   152u,   408u,
      412u,   156u,   160u,   164u,   416u,   168u,   172u,   176u,
      420u,   180u,   184u,   424u,   428u,   188u,   192u,   196u,
      432u,   436u,   200u,   204u,   440u,   208u,   212u,   216u,
      444u,   220u,   448u,   224u,   452u,   228u,   232u,   236u,
      456u,   240u,   460u,   464u,   468u,   244u,   248u,   252u,
      472u,   256u,   260u,   264u,   476u,   268u,   272u,   276u,
      480u,   280u,   284u,   288u,   484u,   488u,   292u,   296u,
      492u,   496u,   300u,   304u,   500u,   504u,   508u,   308u,
};

/* head_dim=256, n_squarefree=157, element_size=4.  Byte offsets for vscatter into a 1024-byte VTCM region. */
static const uint32_t sp_hex_mobius_offsets_hd256_f32[256] __attribute__((aligned(128))) = {
      628u,     0u,     4u,     8u,   632u,    12u,    16u,    20u,
      636u,   640u,    24u,    28u,   644u,    32u,    36u,    40u,
      648u,    44u,   652u,    48u,   656u,    52u,    56u,    60u,
      660u,   664u,    64u,   668u,   672u,    68u,    72u,    76u,
      676u,    80u,    84u,    88u,   680u,    92u,    96u,   100u,
      684u,   104u,   108u,   112u,   688u,   692u,   116u,   120u,
      696u,   700u,   704u,   124u,   708u,   128u,   712u,   132u,
      716u,   136u,   140u,   144u,   720u,   148u,   152u,   724u,
      728u,   156u,   160u,   164u,   732u,   168u,   172u,   176u,
      736u,   180u,   184u,   740u,   744u,   188u,   192u,   196u,
      748u,   752u,   200u,   204u,   756u,   208u,   212u,   216u,
      760u,   220u,   764u,   224u,   768u,   228u,   232u,   236u,
      772u,   240u,   776u,   780u,   784u,   244u,   248u,   252u,
      788u,   256u,   260u,   264u,   792u,   268u,   272u,   276u,
      796u,   280u,   284u,   288u,   800u,   804u,   292u,   296u,
      808u,   812u,   300u,   304u,   816u,   820u,   824u,   308u,
      828u,   312u,   316u,   320u,   832u,   324u,   328u,   836u,
      840u,   332u,   336u,   340u,   844u,   344u,   348u,   352u,
      848u,   356u,   360u,   852u,   856u,   364u,   860u,   368u,
      864u,   868u,   372u,   376u,   872u,   380u,   384u,   388u,
      876u,   392u,   880u,   396u,   884u,   400u,   404u,   408u,
      888u,   892u,   412u,   896u,   900u,   416u,   420u,   904u,
      908u,   424u,   428u,   432u,   912u,   436u,   440u,   444u,
      916u,   448u,   452u,   456u,   920u,   924u,   460u,   464u,
      928u,   468u,   472u,   476u,   932u,   480u,   936u,   484u,
      940u,   488u,   492u,   496u,   944u,   500u,   504u,   948u,
      952u,   508u,   512u,   516u,   956u,   520u,   524u,   528u,
      960u,   532u,   536u,   540u,   964u,   544u,   548u,   552u,
      968u,   972u,   556u,   560u,   976u,   564u,   568u,   572u,
      980u,   576u,   984u,   580u,   988u,   584u,   588u,   592u,
      992u,   596u,   996u,  1000u,  1004u,  1008u,   600u,   604u,
     1012u,   608u,  1016u,   612u,  1020u,   616u,   620u,   624u,
};

/* head_dim=512, n_squarefree=314, element_size=4.  Byte offsets for vscatter into a 2048-byte VTCM region. */
static const uint32_t sp_hex_mobius_offsets_hd512_f32[512] __attribute__((aligned(128))) = {
     1256u,     0u,     4u,     8u,  1260u,    12u,    16u,    20u,
     1264u,  1268u,    24u,    28u,  1272u,    32u,    36u,    40u,
     1276u,    44u,  1280u,    48u,  1284u,    52u,    56u,    60u,
     1288u,  1292u,    64u,  1296u,  1300u,    68u,    72u,    76u,
     1304u,    80u,    84u,    88u,  1308u,    92u,    96u,   100u,
     1312u,   104u,   108u,   112u,  1316u,  1320u,   116u,   120u,
     1324u,  1328u,  1332u,   124u,  1336u,   128u,  1340u,   132u,
     1344u,   136u,   140u,   144u,  1348u,   148u,   152u,  1352u,
     1356u,   156u,   160u,   164u,  1360u,   168u,   172u,   176u,
     1364u,   180u,   184u,  1368u,  1372u,   188u,   192u,   196u,
     1376u,  1380u,   200u,   204u,  1384u,   208u,   212u,   216u,
     1388u,   220u,  1392u,   224u,  1396u,   228u,   232u,   236u,
     1400u,   240u,  1404u,  1408u,  1412u,   244u,   248u,   252u,
     1416u,   256u,   260u,   264u,  1420u,   268u,   272u,   276u,
     1424u,   280u,   284u,   288u,  1428u,  1432u,   292u,   296u,
     1436u,  1440u,   300u,   304u,  1444u,  1448u,  1452u,   308u,
     1456u,   312u,   316u,   320u,  1460u,   324u,   328u,  1464u,
     1468u,   332u,   336u,   340u,  1472u,   344u,   348u,   352u,
     1476u,   356u,   360u,  1480u,  1484u,   364u,  1488u,   368u,
     1492u,  1496u,   372u,   376u,  1500u,   380u,   384u,   388u,
     1504u,   392u,  1508u,   396u,  1512u,   400u,   404u,   408u,
     1516u,  1520u,   412u,  1524u,  1528u,   416u,   420u,  1532u,
     1536u,   424u,   428u,   432u,  1540u,   436u,   440u,   444u,
     1544u,   448u,   452u,   456u,  1548u,  1552u,   460u,   464u,
     1556u,   468u,   472u,   476u,  1560u,   480u,  1564u,   484u,
     1568u,   488u,   492u,   496u,  1572u,   500u,   504u,  1576u,
     1580u,   508u,   512u,   516u,  1584u,   520u,   524u,   528u,
     1588u,   532u,   536u,   540u,  1592u,   544u,   548u,   552u,
     1596u,  1600u,   556u,   560u,  1604u,   564u,   568u,   572u,
     1608u,   576u,  1612u,   580u,  1616u,   584u,   588u,   592u,
     1620u,   596u,  1624u,  1628u,  1632u,  1636u,   600u,   604u,
     1640u,   608u,  1644u,   612u,  1648u,   616u,   620u,   624u,
     1652u,   628u,   632u,   636u,  1656u,  1660u,   640u,   644u,
     1664u,   648u,   652u,   656u,  1668u,   660u,  1672u,   664u,
     1676u,   668u,   672u,  1680u,  1684u,   676u,   680u,  1688u,
     1692u,   684u,   688u,   692u,  1696u,   696u,   700u,   704u,
     1700u,  1704u,   708u,   712u,  1708u,   716u,  1712u,   720u,
     1716u,  1720u,   724u,   728u,  1724u,   732u,   736u,   740u,
     1728u,   744u,  1732u,   748u,  1736u,   752u,   756u,   760u,
     1740u,   764u,   768u,  1744u,  1748u,   772u,   776u,   780u,
     1752u,   784u,   788u,   792u,  1756u,  1760u,   796u,   800u,
     1764u,   804u,   808u,   812u,  1768u,  1772u,   816u,   820u,
     1776u,   824u,  1780u,   828u,  1784u,   832u,  1788u,  1792u,
     1796u,   836u,   840u,   844u,  1800u,   848u,  1804u,  1808u,
     1812u,   852u,   856u,   860u,  1816u,   864u,   868u,   872u,
     1820u,  1824u,   876u,  1828u,  1832u,   880u,   884u,   888u,
     1836u,  1840u,   892u,   896u,  1844u,   900u,   904u,  1848u,
     1852u,   908u,  1856u,   912u,  1860u,   916u,   920u,   924u,
     1864u,   928u,   932u,  1868u,  1872u,   936u,   940u,   944u,
     1876u,   948u,   952u,   956u,  1880u,   960u,   964u,   968u,
     1884u,   972u,   976u,   980u,  1888u,  1892u,   984u,   988u,
     1896u,   992u,   996u,  1000u,  1900u,  1004u,  1904u,  1008u,
     1908u,  1012u,  1016u,  1020u,  1912u,  1024u,  1028u,  1916u,
     1920u,  1924u,  1032u,  1036u,  1928u,  1040u,  1044u,  1048u,
     1932u,  1052u,  1056u,  1060u,  1936u,  1064u,  1068u,  1072u,
     1940u,  1944u,  1076u,  1080u,  1948u,  1084u,  1088u,  1092u,
     1952u,  1096u,  1956u,  1100u,  1960u,  1104u,  1108u,  1112u,
     1964u,  1116u,  1120u,  1968u,  1972u,  1124u,  1128u,  1132u,
     1976u,  1136u,  1140u,  1144u,  1980u,  1148u,  1152u,  1156u,
     1984u,  1160u,  1164u,  1988u,  1992u,  1996u,  1168u,  1172u,
     2000u,  1176u,  1180u,  1184u,  2004u,  1188u,  2008u,  1192u,
     2012u,  1196u,  2016u,  1200u,  2020u,  1204u,  1208u,  2024u,
     2028u,  1212u,  1216u,  1220u,  2032u,  1224u,  1228u,  1232u,
     2036u,  1236u,  1240u,  2040u,  2044u,  1244u,  1248u,  1252u,
};

/* Dispatcher: return the byte-offset table for the requested
 * head_dim, or NULL if unsupported (caller falls back to scalar). */
const uint32_t* sp_hex_mobius_offsets_f32(int head_dim) {
    switch (head_dim) {
    case   64: return sp_hex_mobius_offsets_hd64_f32;
    case  128: return sp_hex_mobius_offsets_hd128_f32;
    case  256: return sp_hex_mobius_offsets_hd256_f32;
    case  512: return sp_hex_mobius_offsets_hd512_f32;
    default: return (const uint32_t*)0;
    }
}

int sp_hex_mobius_supported_head_dim(int head_dim) {
    return sp_hex_mobius_offsets_f32(head_dim) ? 1 : 0;
}

int sp_hex_mobius_n_squarefree(int head_dim) {
    switch (head_dim) {
    case   64: return 39;
    case  128: return 78;
    case  256: return 157;
    case  512: return 314;
    default: return -1;
    }
}
